// Auto-generated by CGAL_SlopeLine_Integrated
// Source: /home/ramkumar/Documents/my_projects/TriDecomp/TriDecomp/testdata/run_quiet/../unit_square.shp (TestSquare) | no reduction
// Points: 4
//

#ifndef POLYGON_OUTPUT_H
#define POLYGON_OUTPUT_H

#include <vector>

// CGAL Headers needed for the types used in this file
#include <CGAL/Exact_predicates_exact_constructions_kernel.h>
#include <CGAL/Point_2.h>

// --- Type Definitions ---
using K     = CGAL::Exact_predicates_exact_constructions_kernel;
using Point = K::Point_2;

std::vector<Point> simple_polygon = {
    Point(-97.0000000000, 32.0000000000),
    Point(-96.0000000000, 32.0000000000),
    Point(-96.0000000000, 33.0000000000),
    Point(-97.0000000000, 33.0000000000)
};

#endif // POLYGON_OUTPUT_H
